apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/owshq-academy/ws-stack-dados-k8s.git'
    path: infra/src/helm-charts/minio-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: '8s-1-29-1-do-0-syd1-1715090730060'
      namespace: deepstorage
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
